before_install:
  - openssl aes-256-cbc -K $encrypted_d0b8e3f713e0_key -iv $encrypted_d0b8e3f713e0_iv -in config/access_tokens.yml.enc -out config/access_tokens.yml -d
script:
  - mysql -e "create database $DATABASE_NAME"
  - bundle exec rake db:migrate test
rvm:
  - 2.1.2
env:
  global:
    - DATABASE_NAME=inch_ci_test
  matrix:
    - DATABASE_URL=mysql2://travis@localhost/$DATABASE_NAME
